// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Register.Database;

#nullable disable

namespace Register.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("CreateNewTables")]
    partial class CreateNewTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Register.Database.Models.BankDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bank_name");

                    b.HasKey("Id");

                    b.ToTable("banks");
                });

            modelBuilder.Entity("Register.Database.Models.CalculationMethodDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CalculationMethodName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("calculation_method_name");

                    b.HasKey("Id");

                    b.ToTable("calculation_methods");
                });

            modelBuilder.Entity("Register.Database.Models.DocumentTypeDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("DocumentTypeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("document_type_name");

                    b.HasKey("Id");

                    b.ToTable("document_types");
                });

            modelBuilder.Entity("Register.Database.Models.GuardianDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("BankId")
                        .HasColumnType("integer")
                        .HasColumnName("bank_id");

                    b.Property<DateOnly>("BeginningDate")
                        .HasColumnType("date")
                        .HasColumnName("beginning_date");

                    b.Property<DateOnly>("Birthday")
                        .HasColumnType("date")
                        .HasColumnName("birthday");

                    b.Property<int>("CalculationMethodId")
                        .HasColumnType("integer")
                        .HasColumnName("calculation_method_id");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("document_number");

                    b.Property<string>("DocumentSeries")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("document_series");

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("document_type_id");

                    b.Property<DateOnly>("EndingDate")
                        .HasColumnType("date")
                        .HasColumnName("ending_date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("Inn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("inn");

                    b.Property<int>("IssuingAuthorityId")
                        .HasColumnType("integer")
                        .HasColumnName("issuing_authority_id");

                    b.Property<DateOnly>("IssuingDate")
                        .HasColumnType("date")
                        .HasColumnName("issuing_date");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<DateOnly>("OpeningDate")
                        .HasColumnType("date")
                        .HasColumnName("opening_date");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("patronymic");

                    b.Property<int>("PensionStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("pension_status_id");

                    b.Property<string>("RecipientAccount")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recipient_account");

                    b.Property<int>("SexId")
                        .HasColumnType("integer")
                        .HasColumnName("sex_id");

                    b.Property<string>("Snils")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("snils");

                    b.Property<int>("TerritoryId")
                        .HasColumnType("integer")
                        .HasColumnName("territory_id");

                    b.HasKey("Id");

                    b.ToTable("guardians");
                });

            modelBuilder.Entity("Register.Database.Models.IssuingAuthorityDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("IssuingAuthorityName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("issuing_authority_name");

                    b.HasKey("Id");

                    b.ToTable("issuing_authorities");
                });

            modelBuilder.Entity("Register.Database.Models.PensionStatusDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("PensionStatusName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pension_status_name");

                    b.HasKey("Id");

                    b.ToTable("pension_statuses");
                });

            modelBuilder.Entity("Register.Database.Models.RelationshipDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("DaysInMonth")
                        .HasColumnType("integer")
                        .HasColumnName("days_in_month");

                    b.Property<DateOnly>("EndingDate")
                        .HasColumnType("date")
                        .HasColumnName("ending_date");

                    b.Property<long>("GuardianId")
                        .HasColumnType("bigint")
                        .HasColumnName("guardian_id");

                    b.Property<long>("WardId")
                        .HasColumnType("bigint")
                        .HasColumnName("ward_id");

                    b.HasKey("Id");

                    b.ToTable("relationships");
                });

            modelBuilder.Entity("Register.Database.Models.SexDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("SexName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sex_name");

                    b.HasKey("Id");

                    b.ToTable("sexes");
                });

            modelBuilder.Entity("Register.Database.Models.TerritoryDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("TerritoryName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("territory_name");

                    b.HasKey("Id");

                    b.ToTable("territories");
                });

            modelBuilder.Entity("Register.Database.Models.UserDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("Email")
                        .HasColumnType("bigint")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<short>("RoleId")
                        .HasColumnType("smallint")
                        .HasColumnName("role_id");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("surname");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Register.Database.Models.UserRoleDto", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.ToTable("user_roles");
                });

            modelBuilder.Entity("Register.Database.Models.WardDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("Birthday")
                        .HasColumnType("date")
                        .HasColumnName("birthday");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("patronymic");

                    b.Property<string>("Snils")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("snils");

                    b.HasKey("Id");

                    b.ToTable("wardens");
                });
#pragma warning restore 612, 618
        }
    }
}
